In [1]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import tensorflow as tf

#  Import and read the charity_data.csv.
import pandas as pd 
application_df = pd.read_csv('Resources/charity_data.csv')
application_df.head()

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [2]:
application_df = application_df.drop(columns = ['EIN'])
for x in application_df.columns:
    print(x, len(application_df[x].unique()))
countsA = application_df['NAME'].value_counts()
countsA

NAME 19568
APPLICATION_TYPE 17
AFFILIATION 6
CLASSIFICATION 71
USE_CASE 5
ORGANIZATION 4
STATUS 2
INCOME_AMT 9
SPECIAL_CONSIDERATIONS 2
ASK_AMT 8747
IS_SUCCESSFUL 2

PARENT BOOSTER USA INC                                                  1260
TOPS CLUB INC                                                            765
UNITED STATES BOWLING CONGRESS INC                                       700
WASHINGTON STATE UNIVERSITY                                              492
AMATEUR ATHLETIC UNION OF THE UNITED STATES INC                          408
                                                                        ...
ST LOUIS SLAM WOMENS FOOTBALL                                              1
AIESEC ALUMNI IBEROAMERICA CORP                                            1
WEALLBLEEDRED ORG INC                                                      1
AMERICAN SOCIETY FOR STANDARDS IN MEDIUMSHIP & PSYCHICAL INVESTIGATI       1
WATERHOUSE CHARITABLE TR                                                   1
Name: NAME, Length: 19568, dtype: int64

In [3]:
names_replace = list(countsA[countsA<5].index)

for name in names_replace:
    application_df['NAME'] = application_df['NAME'].replace(name,"Other")

application_df['NAME'].value_counts()

Other                                                                19803
PARENT BOOSTER USA INC                                                1260
TOPS CLUB INC                                                          765
UNITED STATES BOWLING CONGRESS INC                                     700
WASHINGTON STATE UNIVERSITY                                            492
                                                                     ...
GUILDS OF THE SANTA FE OPERA INC                                         5
FAMILY MOTOR COACH ASSOCIATION                                           5
JAMESTOWN SOCIETY                                                        5
MOST WORSHIPFUL PRINCE HALL GRAND LODGE OF FREE & ACCEPTED MASONS        5
PTA HAWAII CONGRESS                                                      5
Name: NAME, Length: 403, dtype: int64

In [5]:
countsbinning = application_df['CLASSIFICATION'].value_counts()

countsclassification = countsbinning[countsbinning>1]
countsclassification

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
C2800       95
C7100       75
C1300       58
C1280       50
C1230       36
C1400       34
C7200       32
C2300       32
C1240       30
C8000       20
C7120       18
C1500       16
C1800       15
C6000       15
C1250       14
C8200       11
C1238       10
C1278       10
C1235        9
C1237        9
C7210        7
C2400        6
C1720        6
C4100        6
C1257        5
C1600        5
C1260        3
C2710        3
C0           3
C3200        2
C1234        2
C1246        2
C1267        2
C1256        2
Name: CLASSIFICATION, dtype: int64

In [6]:
classifications_to_replace = list (countsbinning[countsbinning<100].index)

for cls in classifications_to_replace:
    application_df['CLASSIFICATION'] = application_df['CLASSIFICATION'].replace(cls,"Other")

application_df['CLASSIFICATION'].value_counts()

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
Other      669
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
Name: CLASSIFICATION, dtype: int64

In [7]:
application_df = pd.get_dummies(application_df,dtype=float)
application_df.head()

,STATUS,ASK_AMT,IS_SUCCESSFUL,NAME_AACE INTERNATIONAL,NAME_ACE MENTOR PROGRAM OF AMERICA INC,NAME_ACTS MINISTRY,NAME_ACTS MISSIONS,NAME_AFRICAN-AMERICAN POSTAL LEAGUE UNITED FOR SUCCESS A-PLUS,NAME_AIR FORCE ASSOCIATION,NAME_ALABAMA FEDERATION OF WOMENS CLUBS,...,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
0,1,5000,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
1,1,108590,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
2,1,5000,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
3,1,6692,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
4,1,142590,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0

In [8]:
y = application_df['IS_SUCCESSFUL'].values
y

X = application_df.drop('IS_SUCCESSFUL', axis=1).values
X

X_train, X_test, y_train, y_test = train_test_split(X,y,random_state = 42)

In [9]:
scaler = StandardScaler()

X_scaler = scaler.fit(X_train)

X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

In [11]:
number_input_features = len( X_train_scaled[0])
hidden_nodes_layer1=80
hidden_nodes_layer2=30
hidden_nodes_layer3=1
nn = tf.keras.models.Sequential()

nn = tf.keras.models.Sequential()

nn.add(tf.keras.layers.Dense(units=hidden_nodes_layer1, input_dim=number_input_features, activation='relu'))

nn.add(tf.keras.layers.Dense(units=hidden_nodes_layer2, activation='relu'))

nn.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

nn.summary()

Model: "sequential_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_3 (Dense)             (None, 80)                36880

 dense_4 (Dense)             (None, 30)                2430

 dense_5 (Dense)             (None, 1)                 31

=================================================================
Total params: 39,341
Trainable params: 39,341
Non-trainable params: 0
_________________________________________________________________

In [12]:
nn.compile(loss = 'binary_crossentropy', optimizer = 'adam', metrics=['accuracy'])
fit_model = nn.fit(X_train_scaled,y_train,validation_split=0.15, epochs=100)

Epoch 1/100
684/684 [==============================] - 2s 1ms/step - loss: 0.4786 - accuracy: 0.7724 - val_loss: 0.4274 - val_accuracy: 0.8010
Epoch 2/100
684/684 [==============================] - 1s 999us/step - loss: 0.4295 - accuracy: 0.7944 - val_loss: 0.4282 - val_accuracy: 0.8002
Epoch 3/100
684/684 [==============================] - 1s 1ms/step - loss: 0.4245 - accuracy: 0.7960 - val_loss: 0.4282 - val_accuracy: 0.7989
Epoch 4/100
684/684 [==============================] - 1s 988us/step - loss: 0.4217 - accuracy: 0.7983 - val_loss: 0.4292 - val_accuracy: 0.7999
Epoch 5/100
684/684 [==============================] - 1s 980us/step - loss: 0.4198 - accuracy: 0.7985 - val_loss: 0.4292 - val_accuracy: 0.7992
Epoch 6/100
684/684 [==============================] - 1s 968us/step - loss: 0.4179 - accuracy: 0.7982 - val_loss: 0.4289 - val_accuracy: 0.7981
Epoch 7/100
684/684 [==============================] - 1s 978us/step - loss: 0.4167 - accuracy: 0.7995 - val_loss: 0.4326 - val_accuracy: 0.8031
Epoch 8/100
684/684 [==============================] - 1s 978us/step - loss: 0.4155 - accuracy: 0.8017 - val_loss: 0.4351 - val_accuracy: 0.8023
Epoch 9/100
684/684 [==============================] - 1s 973us/step - loss: 0.4147 - accuracy: 0.8006 - val_loss: 0.4335 - val_accuracy: 0.8025
Epoch 10/100
684/684 [==============================] - 1s 977us/step - loss: 0.4135 - accuracy: 0.8019 - val_loss: 0.4370 - val_accuracy: 0.8046
Epoch 11/100
684/684 [==============================] - 1s 975us/step - loss: 0.4131 - accuracy: 0.8019 - val_loss: 0.4330 - val_accuracy: 0.8010
Epoch 12/100
684/684 [==============================] - 1s 993us/step - loss: 0.4129 - accuracy: 0.8016 - val_loss: 0.4341 - val_accuracy: 0.8064
Epoch 13/100
684/684 [==============================] - 1s 1ms/step - loss: 0.4122 - accuracy: 0.8025 - val_loss: 0.4388 - val_accuracy: 0.8044
Epoch 14/100
684/684 [==============================] - 1s 979us/step - loss: 0.4117 - accuracy: 0.8018 - val_loss: 0.4417 - val_accuracy: 0.8025
Epoch 15/100
684/684 [==============================] - 1s 1ms/step - loss: 0.4107 - accuracy: 0.8028 - val_loss: 0.4390 - val_accuracy: 0.7979
Epoch 16/100
684/684 [==============================] - 1s 1ms/step - loss: 0.4101 - accuracy: 0.8022 - val_loss: 0.4413 - val_accuracy: 0.8049
Epoch 17/100
684/684 [==============================] - 1s 991us/step - loss: 0.4101 - accuracy: 0.8046 - val_loss: 0.4404 - val_accuracy: 0.8020
Epoch 18/100
684/684 [==============================] - 1s 1ms/step - loss: 0.4097 - accuracy: 0.8043 - val_loss: 0.4391 - val_accuracy: 0.8015
Epoch 19/100
684/684 [==============================] - 1s 1ms/step - loss: 0.4086 - accuracy: 0.8051 - val_loss: 0.4430 - val_accuracy: 0.7981
Epoch 20/100
684/684 [==============================] - 1s 993us/step - loss: 0.4089 - accuracy: 0.8040 - val_loss: 0.4393 - val_accuracy: 0.7999
Epoch 21/100
684/684 [==============================] - 1s 980us/step - loss: 0.4078 - accuracy: 0.8052 - val_loss: 0.4431 - val_accuracy: 0.8025
Epoch 22/100
684/684 [==============================] - 1s 975us/step - loss: 0.4078 - accuracy: 0.8049 - val_loss: 0.4431 - val_accuracy: 0.8015
Epoch 23/100
684/684 [==============================] - 1s 980us/step - loss: 0.4074 - accuracy: 0.8050 - val_loss: 0.4450 - val_accuracy: 0.7987
Epoch 24/100
684/684 [==============================] - 1s 1ms/step - loss: 0.4069 - accuracy: 0.8052 - val_loss: 0.4454 - val_accuracy: 0.8028
Epoch 25/100
684/684 [==============================] - 1s 1ms/step - loss: 0.4065 - accuracy: 0.8053 - val_loss: 0.4468 - val_accuracy: 0.8036
Epoch 26/100
684/684 [==============================] - 1s 1ms/step - loss: 0.4062 - accuracy: 0.8059 - val_loss: 0.4440 - val_accuracy: 0.8005
Epoch 27/100
684/684 [==============================] - 1s 975us/step - loss: 0.4053 - accuracy: 0.8056 - val_loss: 0.4436 - val_accuracy: 0.8012
Epoch 28/100
684/684 [==============================] - 1s 1ms/step - loss: 0.4051 - accuracy: 0.8065 - val_loss: 0.4475 - val_accuracy: 0.7989
Epoch 29/100
684/684 [==============================] - 1s 1ms/step - loss: 0.4051 - accuracy: 0.8068 - val_loss: 0.4474 - val_accuracy: 0.8007
Epoch 30/100
684/684 [==============================] - 1s 994us/step - loss: 0.4043 - accuracy: 0.8064 - val_loss: 0.4461 - val_accuracy: 0.7992
Epoch 31/100
684/684 [==============================] - 1s 980us/step - loss: 0.4046 - accuracy: 0.8067 - val_loss: 0.4450 - val_accuracy: 0.8018
Epoch 32/100
684/684 [==============================] - 1s 974us/step - loss: 0.4038 - accuracy: 0.8076 - val_loss: 0.4458 - val_accuracy: 0.7963
Epoch 33/100
684/684 [==============================] - 1s 960us/step - loss: 0.4033 - accuracy: 0.8064 - val_loss: 0.4466 - val_accuracy: 0.7974
Epoch 34/100
684/684 [==============================] - 1s 963us/step - loss: 0.4032 - accuracy: 0.8066 - val_loss: 0.4510 - val_accuracy: 0.7953
Epoch 35/100
684/684 [==============================] - 1s 969us/step - loss: 0.4027 - accuracy: 0.8071 - val_loss: 0.4486 - val_accuracy: 0.7987
Epoch 36/100
684/684 [==============================] - 1s 966us/step - loss: 0.4030 - accuracy: 0.8074 - val_loss: 0.4445 - val_accuracy: 0.7999
Epoch 37/100
684/684 [==============================] - 1s 971us/step - loss: 0.4025 - accuracy: 0.8072 - val_loss: 0.4478 - val_accuracy: 0.7955
Epoch 38/100
684/684 [==============================] - 1s 969us/step - loss: 0.4023 - accuracy: 0.8078 - val_loss: 0.4513 - val_accuracy: 0.8007
Epoch 39/100
684/684 [==============================] - 1s 968us/step - loss: 0.4019 - accuracy: 0.8073 - val_loss: 0.4504 - val_accuracy: 0.7989
Epoch 40/100
684/684 [==============================] - 1s 976us/step - loss: 0.4015 - accuracy: 0.8079 - val_loss: 0.4519 - val_accuracy: 0.7999
Epoch 41/100
684/684 [==============================] - 1s 974us/step - loss: 0.4008 - accuracy: 0.8079 - val_loss: 0.4550 - val_accuracy: 0.7987
Epoch 42/100
684/684 [==============================] - 1s 962us/step - loss: 0.4017 - accuracy: 0.8081 - val_loss: 0.4585 - val_accuracy: 0.8007
Epoch 43/100
684/684 [==============================] - 1s 965us/step - loss: 0.4007 - accuracy: 0.8081 - val_loss: 0.4633 - val_accuracy: 0.8020
Epoch 44/100
684/684 [==============================] - 1s 960us/step - loss: 0.4006 - accuracy: 0.8098 - val_loss: 0.4462 - val_accuracy: 0.8015
Epoch 45/100
684/684 [==============================] - 1s 955us/step - loss: 0.3999 - accuracy: 0.8094 - val_loss: 0.4595 - val_accuracy: 0.8012
Epoch 46/100
684/684 [==============================] - 1s 980us/step - loss: 0.3998 - accuracy: 0.8088 - val_loss: 0.4583 - val_accuracy: 0.8007
Epoch 47/100
684/684 [==============================] - 1s 961us/step - loss: 0.3999 - accuracy: 0.8093 - val_loss: 0.4573 - val_accuracy: 0.7992
Epoch 48/100
684/684 [==============================] - 1s 963us/step - loss: 0.3992 - accuracy: 0.8095 - val_loss: 0.4618 - val_accuracy: 0.7997
Epoch 49/100
684/684 [==============================] - 1s 976us/step - loss: 0.3992 - accuracy: 0.8083 - val_loss: 0.4590 - val_accuracy: 0.7948
Epoch 50/100
684/684 [==============================] - 1s 969us/step - loss: 0.3997 - accuracy: 0.8094 - val_loss: 0.4558 - val_accuracy: 0.8005
Epoch 51/100
684/684 [==============================] - 1s 964us/step - loss: 0.3990 - accuracy: 0.8088 - val_loss: 0.4540 - val_accuracy: 0.7992
Epoch 52/100
684/684 [==============================] - 1s 978us/step - loss: 0.3991 - accuracy: 0.8090 - val_loss: 0.4538 - val_accuracy: 0.8007
Epoch 53/100
684/684 [==============================] - 1s 983us/step - loss: 0.3989 - accuracy: 0.8100 - val_loss: 0.4572 - val_accuracy: 0.8012
Epoch 54/100
684/684 [==============================] - 1s 982us/step - loss: 0.3984 - accuracy: 0.8091 - val_loss: 0.4592 - val_accuracy: 0.7984
Epoch 55/100
684/684 [==============================] - 1s 977us/step - loss: 0.3979 - accuracy: 0.8097 - val_loss: 0.4577 - val_accuracy: 0.8005
Epoch 56/100
684/684 [==============================] - 1s 967us/step - loss: 0.3981 - accuracy: 0.8086 - val_loss: 0.4601 - val_accuracy: 0.7994
Epoch 57/100
684/684 [==============================] - 1s 986us/step - loss: 0.3977 - accuracy: 0.8099 - val_loss: 0.4583 - val_accuracy: 0.7997
Epoch 58/100
684/684 [==============================] - 1s 981us/step - loss: 0.3976 - accuracy: 0.8099 - val_loss: 0.4606 - val_accuracy: 0.7999
Epoch 59/100
684/684 [==============================] - 1s 956us/step - loss: 0.3977 - accuracy: 0.8099 - val_loss: 0.4633 - val_accuracy: 0.7948
Epoch 60/100
684/684 [==============================] - 1s 961us/step - loss: 0.3978 - accuracy: 0.8097 - val_loss: 0.4663 - val_accuracy: 0.7999
Epoch 61/100
684/684 [==============================] - 1s 960us/step - loss: 0.3976 - accuracy: 0.8099 - val_loss: 0.4599 - val_accuracy: 0.7976
Epoch 62/100
684/684 [==============================] - 1s 963us/step - loss: 0.3969 - accuracy: 0.8101 - val_loss: 0.4618 - val_accuracy: 0.7989
Epoch 63/100
684/684 [==============================] - 1s 969us/step - loss: 0.3975 - accuracy: 0.8095 - val_loss: 0.4664 - val_accuracy: 0.8012
Epoch 64/100
684/684 [==============================] - 1s 966us/step - loss: 0.3967 - accuracy: 0.8091 - val_loss: 0.4634 - val_accuracy: 0.7989
Epoch 65/100
684/684 [==============================] - 1s 980us/step - loss: 0.3963 - accuracy: 0.8098 - val_loss: 0.4657 - val_accuracy: 0.8010
Epoch 66/100
684/684 [==============================] - 1s 959us/step - loss: 0.3967 - accuracy: 0.8091 - val_loss: 0.4708 - val_accuracy: 0.8015
Epoch 67/100
684/684 [==============================] - 1s 955us/step - loss: 0.3972 - accuracy: 0.8103 - val_loss: 0.4674 - val_accuracy: 0.8010
Epoch 68/100
684/684 [==============================] - 1s 970us/step - loss: 0.3963 - accuracy: 0.8104 - val_loss: 0.4636 - val_accuracy: 0.8005
Epoch 69/100
684/684 [==============================] - 1s 970us/step - loss: 0.3961 - accuracy: 0.8107 - val_loss: 0.4692 - val_accuracy: 0.8010
Epoch 70/100
684/684 [==============================] - 1s 963us/step - loss: 0.3960 - accuracy: 0.8102 - val_loss: 0.4637 - val_accuracy: 0.7987
Epoch 71/100
684/684 [==============================] - 1s 956us/step - loss: 0.3961 - accuracy: 0.8108 - val_loss: 0.4708 - val_accuracy: 0.7981
Epoch 72/100
684/684 [==============================] - 1s 969us/step - loss: 0.3960 - accuracy: 0.8107 - val_loss: 0.4654 - val_accuracy: 0.7989
Epoch 73/100
684/684 [==============================] - 1s 958us/step - loss: 0.3960 - accuracy: 0.8100 - val_loss: 0.4739 - val_accuracy: 0.7981
Epoch 74/100
684/684 [==============================] - 1s 963us/step - loss: 0.3952 - accuracy: 0.8105 - val_loss: 0.4714 - val_accuracy: 0.7971
Epoch 75/100
684/684 [==============================] - 1s 970us/step - loss: 0.3960 - accuracy: 0.8106 - val_loss: 0.4691 - val_accuracy: 0.8007
Epoch 76/100
684/684 [==============================] - 1s 964us/step - loss: 0.3960 - accuracy: 0.8115 - val_loss: 0.4728 - val_accuracy: 0.8020
Epoch 77/100
684/684 [==============================] - 1s 961us/step - loss: 0.3956 - accuracy: 0.8099 - val_loss: 0.4601 - val_accuracy: 0.7994
Epoch 78/100
684/684 [==============================] - 1s 972us/step - loss: 0.3958 - accuracy: 0.8104 - val_loss: 0.4651 - val_accuracy: 0.7999
Epoch 79/100
684/684 [==============================] - 1s 965us/step - loss: 0.3959 - accuracy: 0.8107 - val_loss: 0.4790 - val_accuracy: 0.7997
Epoch 80/100
684/684 [==============================] - 1s 971us/step - loss: 0.3948 - accuracy: 0.8106 - val_loss: 0.4788 - val_accuracy: 0.7997
Epoch 81/100
684/684 [==============================] - 1s 962us/step - loss: 0.3957 - accuracy: 0.8105 - val_loss: 0.4769 - val_accuracy: 0.8002
Epoch 82/100
684/684 [==============================] - 1s 970us/step - loss: 0.3954 - accuracy: 0.8109 - val_loss: 0.4811 - val_accuracy: 0.8007
Epoch 83/100
684/684 [==============================] - 1s 966us/step - loss: 0.3955 - accuracy: 0.8107 - val_loss: 0.4705 - val_accuracy: 0.8010
Epoch 84/100
684/684 [==============================] - 1s 971us/step - loss: 0.3948 - accuracy: 0.8118 - val_loss: 0.4700 - val_accuracy: 0.7963
Epoch 85/100
684/684 [==============================] - 1s 958us/step - loss: 0.3949 - accuracy: 0.8111 - val_loss: 0.4676 - val_accuracy: 0.8010
Epoch 86/100
684/684 [==============================] - 1s 969us/step - loss: 0.3943 - accuracy: 0.8110 - val_loss: 0.4718 - val_accuracy: 0.7974
Epoch 87/100
684/684 [==============================] - 1s 951us/step - loss: 0.3948 - accuracy: 0.8113 - val_loss: 0.4679 - val_accuracy: 0.7989
Epoch 88/100
684/684 [==============================] - 1s 978us/step - loss: 0.3942 - accuracy: 0.8113 - val_loss: 0.4718 - val_accuracy: 0.7966
Epoch 89/100
684/684 [==============================] - 1s 957us/step - loss: 0.3942 - accuracy: 0.8109 - val_loss: 0.4799 - val_accuracy: 0.8010
Epoch 90/100
684/684 [==============================] - 1s 958us/step - loss: 0.3948 - accuracy: 0.8109 - val_loss: 0.4774 - val_accuracy: 0.7989
Epoch 91/100
684/684 [==============================] - 1s 954us/step - loss: 0.3944 - accuracy: 0.8113 - val_loss: 0.4756 - val_accuracy: 0.7994
Epoch 92/100
684/684 [==============================] - 1s 960us/step - loss: 0.3946 - accuracy: 0.8107 - val_loss: 0.4687 - val_accuracy: 0.7984
Epoch 93/100
684/684 [==============================] - 1s 960us/step - loss: 0.3946 - accuracy: 0.8112 - val_loss: 0.4764 - val_accuracy: 0.8007
Epoch 94/100
684/684 [==============================] - 1s 953us/step - loss: 0.3942 - accuracy: 0.8102 - val_loss: 0.4741 - val_accuracy: 0.7987
Epoch 95/100
684/684 [==============================] - 1s 955us/step - loss: 0.3940 - accuracy: 0.8108 - val_loss: 0.4757 - val_accuracy: 0.7971
Epoch 96/100
684/684 [==============================] - 1s 964us/step - loss: 0.3939 - accuracy: 0.8114 - val_loss: 0.4737 - val_accuracy: 0.7974
Epoch 97/100
684/684 [==============================] - 1s 964us/step - loss: 0.3943 - accuracy: 0.8116 - val_loss: 0.4699 - val_accuracy: 0.8007
Epoch 98/100
684/684 [==============================] - 1s 954us/step - loss: 0.3934 - accuracy: 0.8111 - val_loss: 0.4797 - val_accuracy: 0.7992
Epoch 99/100
684/684 [==============================] - 1s 944us/step - loss: 0.3940 - accuracy: 0.8113 - val_loss: 0.4759 - val_accuracy: 0.7997
Epoch 100/100
684/684 [==============================] - 1s 980us/step - loss: 0.3941 - accuracy: 0.8104 - val_loss: 0.4795 - val_accuracy: 0.7994

In [13]:
model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 0s - loss: 0.5063 - accuracy: 0.7854 - 158ms/epoch - 589us/step
Loss: 0.5062554478645325, Accuracy: 0.7854227423667908

In [8]:
from google.colab import files

nn.save('AlphabetSoupCharity_Optimization.h5')
files.download('AlphabetSoupCharity_Optimization.h5')

ModuleNotFoundError: No module named 'termios'